In [2]:
import torch
import torch.nn as nn 
from torchvision.transforms import Compose

In [3]:
nn.Linear(in_features=10,out_features=10)

Linear(in_features=10, out_features=10, bias=True)

## 一、张量的数据类型：

In [4]:
import torch ## 导入所需库

In [7]:
torch.tensor([1.2,3.4]).dtype ## 获取张量的数据类型

torch.float32

#### 设置默认数据类型

In [10]:
torch.set_default_tensor_type(torch.DoubleTensor) ## torch.set_default_tensor_type 用于设置默认的数据类型（该函数只支持浮点型的设置）
torch.tensor([1.2,3.4]).dtype

torch.float64

#### 浮点型转为其他数据类型的方法

In [12]:
a= torch.tensor([1.2,3.4])
print("a.dtype：",a.dtype)
print("a.long：",a.long().dtype)  
print("a.int：",a.int().dtype)    
print("a.float：",a.float().dtype)

a.dtype： torch.float64
a.long： torch.int64
a.int： torch.int32
a.float： torch.float32


#### 设置回 tensor 默认数据类型

In [14]:
torch.set_default_tensor_type(torch.FloatTensor) ## torch.set_default_tensor_type 用于设置默认的数据类型（该函数只支持浮点型的设置）
torch.tensor([1.2,3.4]).dtype

torch.float32

#### 获取默认的数据类型

In [15]:
torch.get_default_dtype()

torch.float32

## 二、张量的生成


tensor 和 Tensor 的区别：

#### 区别1：

* torch.Tensor(data)：是将输入的data转化torch.FloatTensor
* torch.tensor(data)：(当你未指定dype的类型时)将data转化为torch.FloatTensor、torch.LongTensor、torch.DoubleTensor等类型，转化类型依据于data的类型或者dtype的值

#### 区别2：

* 使用如下语句：tensor_without_data = torch.Tensor()可以创建一个空的FloatTensor，而当你使用tensor_without_data = torch.tensor()时候则会报错。

#### 总结：

* 所以 torch.Tensor 应该说是同时具有 torch.tensor 和 torch.empty 的功能，但是使用 torch.Tensor 可能会令人困惑，所以最好还是使用 torch.tensor 和 torch.empty ，而不是 torch.Tensor。

### 1、 torch.tensor()  函数生成张量

In [41]:
A= torch.tensor([[1,1],[2,2]])
A

tensor([[1, 1],
        [2, 2]])

#### 使用shape 和size 可以查看张量的维度和形状

In [46]:
print(A.shape)   ## 获取张量的维度
print(A.size())  ## 获取张量的形状大小

## size 和 shape 的区别：1、shape 是属性 ，size 是方法  2、size 可以传参查看某个子张量矩阵的维度大小

print(A.numel())   ## 计算张量中包含的元素的数量

torch.Size([2, 2])
torch.Size([2, 2])
4


#### 使用 torch.tensor 时可以使用 dtype 来指定张量的数据类型，使用 requires_grad 来指定是否需要计算梯度，只有计算了梯度的张鲁昂才能在深度网络优化时根据梯度大小进行更新。

In [54]:
B = torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

#### 下面计算 sum($B^2$) 的梯度

需要注意的是只有浮点型才能计算张量的梯度

In [55]:
y= B.pow(2).sum()
print(y.backward())
print(B.grad)       # B方 的梯度为 2B

None
tensor([2., 4., 6.])


### 2、 torch.Tensor()  函数生成张量

In [57]:
C = torch.Tensor([1,2,3,4])    ## 根据 python 列表生成张量c
C

tensor([1., 2., 3., 4.])

In [59]:
D = torch.Tensor(2,3)             ## 创建具有特定大小的张量
D

tensor([[0.0000, 1.8750, 0.0000],
        [2.0000, 0.0000, 2.1250]])

In [63]:
## 使用torch.**_like() 系列函数生成指定张量维度相同、性质相似的张量
print(torch.ones_like(D))   ## 创建一个与D相同大小和类型的全1张量
print(torch.zeros_like(D))  ## 创建一个与D相同大小和类型的全0张量
print(torch.rand_like(D))  ## 创建一个与D相同大小和类型的随机张量

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5760, 0.5961, 0.5157],
        [0.9368, 0.6834, 0.9161]])


In [69]:
## 创建一个类型相反但是尺寸不同的张量
E = [[1,2],[3,4]]
E = D.new_tensor(E)
print('D.dtype：',D.dtype)
print('E.dtype：',E.dtype)

D.dtype： torch.float32
E.dtype： torch.float32


### 3、张量和NumPy数据相互转换

In [72]:
import numpy as np

F = np.ones((3,3))
## 使用 torch.as_tensor() 函数和 torch.from_numpy() 函数可以将数组转为 PyTorch 张量。
Ftensor = torch.as_tensor(F)
print(Ftensor)

Ftensor = torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### 4、随机数生成张量

In [77]:
## 通过指定指定均值和标准差生成随机数
torch.manual_seed(123)                        ## 指定随机种子，不指定每一次运行的结构都不一样
A=torch.normal(mean=0.0,std=torch.tensor(1.0))
A

tensor(-0.1115)

In [85]:
## 通过指定指定均值和标准差生成随机数
torch.manual_seed(123)
A=torch.normal(mean=0.0,std=torch.arange(1,5.0))
A

tensor([-0.0283,  2.8440, -1.1658, -3.5613])

### 5、其他生成张量的函数

In [87]:
torch.arange(start=0,end=10,step=2)

tensor([0, 2, 4, 6, 8])

In [89]:
torch.linspace(start=0,end=10,steps=5) ## 在范围内生成固定数量的等间隔张量

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [90]:
torch.logspace(start=0,end=10,steps=5) ## 生成以对数为间隔的张量

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

## 三、张量操作

### 1、改变张量的形状

In [93]:
A= torch.arange(12.0).reshape(3,4) ## reshape 设置张量的大小
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [96]:
torch.reshape(input=A,shape=(2,-1))   ## 设置形状 （行为2，列为任意）

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [113]:
A = A.resize_(2,6)  ## 设置形状
A

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [124]:
B=torch.arange(10.0,19.0).reshape(3,3)  
A.resize_as_(B)  ##  可以让 A 设置成 B 的形状
A

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [125]:
A = torch.arange(12.0).reshape(2,6)
B = torch.unsqueeze(A,dim=0)    ## 在指定维度插入尺寸为1的新张量
print(B.shape)
B

torch.Size([1, 2, 6])


tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]]])

In [126]:
## torch.squeeze()   ## 函数移除所有维度为1 的维度
C = B.unsqueeze(dim=3)
print('C.shape：',C.shape)
D = torch.squeeze(C)
print('D.shape：',D.shape)

C.shape： torch.Size([1, 2, 6, 1])
D.shape： torch.Size([2, 6])


In [129]:
## 使用 .enpand 方法扩展张量
A=torch.arange(3)
B=A.expand(3,-1)
B

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [130]:
## 使用 .enpand_as() 方法扩展张量

C = torch.arange(6).reshape(2,3)
B = A.expand_as(C)               ## 张量A根据C的形状来进行扩展，得到新的张量
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [131]:
## 使用repeat 方法扩展张量，根据指定形状重复填充
D = B.repeat(1,2,2)
print(D)
D.shape

tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])


torch.Size([1, 4, 6])

### 2、获取张量中的元素

#### 在张量中利用切片提取元素和在Numpy 中使用的方法是一样的。

In [136]:
## 利用切片提取元素
A= torch.arange(12).reshape(1,3,4)
print(A)
print(A[0])
print(A[0,0:2,:])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


#### torch 中还可以将索引设置为相应的布尔值，然后提取为真是条件下的内容，例如找到A中取值大于5的元素

In [141]:
B = -A
print(torch.where(A>5,A,B))   ## 当满足 A >5时返回x所对应位置值，为false时返回y的值

## 获取 A 中大于5 的元素
A[A>5]

tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])


tensor([ 6,  7,  8,  9, 10, 11])

### 3、拼接和拆分

In [165]:
## 在给定维度中链接给定的张量序列
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(0,10,6).reshape(2,3)


print('A.shape：',A.shape)
print('B.shape：',B.shape)
print(A)
print(B)
print('\n')

## 在0维度连接张量
C = torch.cat((A,B),dim=0)
print('C.shape：',C.shape)
print(C)
print('\n')
## 在1维度连接张量
D = torch.cat((A,B),dim=1)
print('D.shape：',D.shape)
print(D)

E =torch.cat((A[:,1:2],A,B),dim=1)
E

A.shape： torch.Size([2, 3])
B.shape： torch.Size([2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


C.shape： torch.Size([4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


D.shape： torch.Size([2, 6])
tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])


tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])

In [163]:
## torch.stack 可以将多个张量按照指定的新维度进行拼接
F = torch.stack((A,B),dim=0)
print(F)
print(F.shape)  ## 新创建了一个维度

print('\n')
G = torch.stack((A,B),dim=2) 
print(G)
print(G.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])


tensor([[[ 0.,  0.],
         [ 1.,  2.],
         [ 2.,  4.]],

        [[ 3.,  6.],
         [ 4.,  8.],
         [ 5., 10.]]])
torch.Size([2, 3, 2])


In [174]:
## torch.chunk 可以将张量分割为特定数量的块；torch.split  可以将张量分割为特定数量块的同时指定每个块的大小
print(E)
print('\n')

print(torch.chunk(E,2,dim=0))
print('\n')

D1,D2 = torch.chunk(D,2,dim=1) 
print(D1)
print(D2)
print('\n')

## 特别的如果给定维度dim 的张量大小不能被块整除，则最后一块将最小。
E1,E2,E3 = torch.chunk(E,3,dim=1) 
print(E1)
print(E2)
print(E3)
print('\n')

## 将张量切分为块，并且指定每个块的大小
D1,D2,D3 = torch.split(D,[1,2,3],dim=1)
print(D1)
print(D2)
print(D3)

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])


(tensor([[1., 0., 1., 2., 0., 2., 4.]]), tensor([[ 4.,  3.,  4.,  5.,  6.,  8., 10.]]))


tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


tensor([[1., 0., 1.],
        [4., 3., 4.]])
tensor([[2., 0., 2.],
        [5., 6., 8.]])
tensor([[ 4.],
        [10.]])


tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


## 四、张量的计算

### 1、比较大小

In [185]:
A = torch.tensor([1,2,3,4,5,6])
B = torch.arange(1,7)
C = torch.unsqueeze(B,dim=0)

print('A: ',A)
print('B: ',B)
print('C: ',C)
print('\n')

## 计算元素是否相等 torch.eq() 函数
print(torch.eq(A,B))
print(torch.eq(A,C))
print('\n')

## 判断两个张量是否具有相同的形状和元素 torch.equal() 函数
print(torch.equal(A,B))
print(torch.equal(A,C))

A:  tensor([1, 2, 3, 4, 5, 6])
B:  tensor([1, 2, 3, 4, 5, 6])
C:  tensor([[1, 2, 3, 4, 5, 6]])


tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


True
False


In [197]:
## 逐元素比较大于等于
print(torch.ge(A,B))
print(torch.ge(A,C))
print('\n')

## 逐元素比较大于
print(torch.gt(A,B))
print(torch.gt(A,C))
print('\n')

## 逐元素比较小于等于
print(torch.le(A,B))
print(torch.le(A,C))
print('\n')

## 逐元素比较小于
print(torch.lt(A,B))
print(torch.lt(A,C))
print('\n')

## 逐元素比较不相等
print(torch.ne(A,B))
print('\n')

## 判断缺失值
print(torch.isnan(torch.tensor([1,2,3,float('nan')])))


tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


tensor([False, False, False, False, False, False])


tensor([False, False, False,  True])


### 2、基本运算

张量的基本运算是逐元素运算，很简单，以乘法为例：

In [203]:
A = torch.arange(10).reshape(2,5)
B = torch.linspace(10,20,steps=10).reshape(2,5)
print(A)
print(B)
print(A*B)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10.0000, 11.1111, 12.2222, 13.3333, 14.4444],
        [15.5556, 16.6667, 17.7778, 18.8889, 20.0000]])
tensor([[  0.0000,  11.1111,  24.4444,  40.0000,  57.7778],
        [ 77.7778, 100.0000, 124.4445, 151.1111, 180.0000]])


张量的矩阵运算：

In [209]:
## 矩阵的转置
C = torch.t(A)
print(C)

## 矩阵乘法,注意，矩阵 A 的列数要等于 C 的行数
A.matmul(C)

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])


tensor([[ 30,  80],
        [ 80, 255]])

统计相关的运算：

In [235]:
torch.manual_seed(123)
A=torch.randn([1,10])  ## 生成随机张量
print(A)
print(A.max())       ## torch.max() 查看最大值
print(A.argmax())    ## torch.argmax() 查看最大值的位置
print('\n')
print(A.min())       ## torch.max() 查看最大值
print(A.argmin())    ## torch.argmax() 查看最大值的位置

B =A.reshape(2,5)
B

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
          0.3239, -0.1085]])
tensor(0.3239)
tensor(8)


tensor(-1.1969)
tensor(4)


tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])

In [243]:
## torch.sort() 可以对张量进行排序，输出从小到大的排序结果和对应的元素索引位置
### 1D 张量
display(torch.sort(A))

display(torch.sort(A,descending=True))
print('\n')

### 2D张量
Bsort,Bsort_id=torch.sort(B)
print('Bsort: ',Bsort)
print('Bsort_id: ',Bsort_id)

torch.return_types.sort(values=tensor([[-1.1969, -0.9724, -0.7550, -0.3696, -0.2404, -0.1115, -0.1085,  0.1204,
          0.2093,  0.3239]]), indices=tensor([[4, 6, 7, 2, 3, 0, 9, 1, 5, 8]]))

torch.return_types.sort(values=tensor([[ 0.3239,  0.2093,  0.1204, -0.1085, -0.1115, -0.2404, -0.3696, -0.7550,
         -0.9724, -1.1969]]), indices=tensor([[8, 5, 1, 9, 0, 3, 2, 7, 6, 4]]))



Bsort:  tensor([[-1.1969, -0.3696, -0.2404, -0.1115,  0.1204],
        [-0.9724, -0.7550, -0.1085,  0.2093,  0.3239]])
Bsort_id:  tensor([[4, 2, 3, 0, 1],
        [1, 2, 4, 0, 3]])


In [247]:
## 获取张量中最大的前K个数值和索引位置
display(torch.topk(A,2))

### 2D 数据
display(torch.topk(B,2,dim=0))

## 获取张量中最小的第K个数值和索引位置
display(torch.kthvalue(A,2))


torch.return_types.topk(values=tensor([[0.3239, 0.2093]]), indices=tensor([[8, 5]]))

torch.return_types.topk(values=tensor([[ 0.2093,  0.1204, -0.3696,  0.3239, -0.1085],
        [-0.1115, -0.9724, -0.7550, -0.2404, -1.1969]]), indices=tensor([[1, 0, 0, 1, 1],
        [0, 1, 1, 0, 0]]))

torch.return_types.kthvalue(values=tensor([-0.9724]), indices=tensor([6]))

In [270]:
print('-------- Tensor B -------')
display(B)

## torch.mean() 平均数
print('-------- mean -------')
display(torch.mean(B,dim=1,keepdim=True))          ## keepdim 用于指定是否保留原维度，为False 时mean 会减少一维
# display(torch.mean(B,dim=1).shape)               ## torch.Size([2])
# display(torch.mean(B,dim=1,keepdim=True).shape)  ## torch.Size([2, 1])

## torch.sum()  加法
print('-------- sum -------')
display(torch.sum(B,dim=1,keepdim=True))          


## torch.cumsum()  累加
print('-------- cumsum -------')
display(torch.cumsum(B,dim=1))          


## torch.median()
print('-------- median -------')
display(torch.median(B,dim=1))          
 
## torch.cumprod() 累乘
print('-------- cumprod -------')
display(torch.cumprod(B,dim=1))          


## torch.std() 标准差
print('-------- std -------')
display(torch.std(B,dim=1))          

-------- Tensor B -------


tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])

-------- mean -------


tensor([[-0.3596],
        [-0.2606]])

-------- sum -------


tensor([[-1.7981],
        [-1.3028]])

-------- cumsum -------


tensor([[-0.1115,  0.0089, -0.3607, -0.6012, -1.7981],
        [ 0.2093, -0.7631, -1.5181, -1.1942, -1.3028]])

-------- median -------


torch.return_types.median(values=tensor([-0.2404, -0.1085]), indices=tensor([3, 4]))

-------- cumprod -------


tensor([[-0.1115, -0.0134,  0.0050, -0.0012,  0.0014],
        [ 0.2093, -0.2035,  0.1536,  0.0498, -0.0054]])

-------- std -------


tensor([0.5018, 0.5781])