## LSTM

In [3]:
from torch.nn import LSTM
import torch

In [4]:
lstm = LSTM(input_size = 4,hidden_size=5,batch_first=True)
inputs = torch.rand(2,3,4)
outputs,(hn,cn) = lstm(inputs)

#### output 为输出序列的隐藏层，hn为最后一个时刻的隐藏层，cn为最后一个时刻的记忆细胞

In [5]:
outputs ## 输出两个序列，每个序列长度为3 大小为5

tensor([[[ 0.1764,  0.0533,  0.0934,  0.0364, -0.0713],
         [ 0.2261,  0.0169,  0.1632,  0.2033, -0.1346],
         [ 0.2179, -0.0016,  0.1605,  0.2536, -0.1547]],

        [[ 0.1907,  0.0615,  0.0986,  0.0710, -0.0780],
         [ 0.2485,  0.0146,  0.1463,  0.1446, -0.1274],
         [ 0.2547,  0.0395,  0.1722,  0.1309, -0.1494]]],
       grad_fn=<TransposeBackward0>)

#### 最后一个时刻的隐藏层，值与output 真能干最后一个时刻相同

In [6]:
hn

tensor([[[ 0.2179, -0.0016,  0.1605,  0.2536, -0.1547],
         [ 0.2547,  0.0395,  0.1722,  0.1309, -0.1494]]],
       grad_fn=<StackBackward>)

In [8]:
hn[-1]

tensor([[ 0.2179, -0.0016,  0.1605,  0.2536, -0.1547],
        [ 0.2547,  0.0395,  0.1722,  0.1309, -0.1494]],
       grad_fn=<SelectBackward>)

In [7]:
cn

tensor([[[ 0.5298, -0.0029,  0.2957,  0.5308, -0.4250],
         [ 0.5133,  0.0848,  0.2943,  0.2930, -0.4678]]],
       grad_fn=<StackBackward>)